USE d1;
CREATE TABLE emp (sal INT, job VARCHAR(30));
INSERT INTO emp VALUES (30000, 'Manager');
INSERT INTO emp VALUES (20000, "Developer");
INSERT INTO emp VALUES (15000,'Tester');
INSERT INTO emp VALUES (25800, 'HR');
INSERT INTO emp VALUES (18000, 'Analyst');
SELECT sal AS salary, job AS job_desc, sal * 12 AS annual_salary FROM emp;
ALTER TABLE emp ADD department VARCHAR (30);
ALTER TABLE emp ADD department VARCHAR (30);
UPDATE emp SET department = "Manager" WHERE job - "Developer";
UPDATE emp SET department = "Developer" WHERE job = 'Tester';
UPDATE emp SET department = 'Tester' WHERE Job = "HR";
UPDATE emp SET department = "HR" WHERE job = 'Manager';
UPDATE emp SET department = "Abalyst" WHERE job = 'dev';
SELECT sal AS salary, job AS job_desc, department, sal * 12 AS annual_salary FROM emp;
DESCRIBE emp;